function createPlaybackTransportState() {
  return {
    playbackRange: {
      startOffset: 0,
      endOffset: null,
      origin: "cursor",
      loop: false,
    },
    activePlaybackRange: null,
    activePlaybackEndAbcOffset: null,
    activePlaybackEndSymbol: null,
    activeLoopRange: null,
    playbackStartArmed: false,
    playbackRunId: 0,
    lastTraceRunId: 0,
    lastTracePlaybackIdx: null,
    lastTraceTimestamp: null,
    playbackTraceSeq: 0,

    practiceTempoMultiplier: 1,
    playbackLoopEnabled: false,
    playbackLoopFromMeasure: 0,
    playbackLoopToMeasure: 0,
    playbackLoopTuneId: null,
    currentPlaybackPlan: null,
    pendingPlaybackPlan: null,
    playbackSkipGchordsOnce: false,
    playbackIgnoreRepeatsOnce: false,
    transportPlayheadOffset: 0,
    transportJumpHighlightActive: false,
    suppressTransportJumpClearOnce: false,

    player: null,
    playerConfig: null,
    isPlaying: false,
    isPaused: false,
    suppressOnEnd: false,
    desiredPlayerSpeed: 1,
    lastPlaybackIdx: null,
    lastRenderIdx: null,
    lastStartPlaybackIdx: 0,
    resumeStartIdx: null,
    pausedSelectionSignature: null,
    playbackState: null,
    playbackIndexOffset: 0,
    waitingForFirstNote: false,
    isPreviewing: false,

    lastPlaybackMeta: null,
    lastPlaybackPayloadCache: null,
    lastPreparedPlaybackKey: null,
    playbackNoteTrace: [],
    playbackParseErrors: [],
    playbackSanitizeWarnings: [],
    lastPlaybackTuneInfo: null,
    lastPlaybackOnIstart: null,
    lastPlaybackHasParts: false,
    lastPlaybackChordOnBarError: false,
    lastPlaybackMidiDrumVoiceCompatSeen: false,
    lastPlaybackMeterMismatchWarning: null,
    lastPlaybackRepeatShortBarWarning: null,
    lastPlaybackKeyOrderWarning: null,
    playbackStartToken: 0,
    lastPlaybackGuardMessage: "",
    lastPlaybackAbortMessage: "",
    lastPlaybackException: null,
    playbackNeedsReprepare: false,
  };
}

export {
  createPlaybackTransportState,
};
